import { NextResponse } from "next/server";

export async function GET() {
  return NextResponse.json(
    {
      name: "CeloFX",
      version: "1.0.0",
      protocolVersion: "2025-06-18",
      description:
        "Autonomous FX arbitrage agent — monitors Mento & Uniswap V3 on Celo, compares with real forex rates, and executes stablecoin swaps when spreads are profitable.",
      tools: [
        {
          name: "get_mento_rates",
          description:
            "Get live Mento Broker on-chain stablecoin exchange rates on Celo compared with real forex rates. Returns spread analysis for arbitrage.",
          inputSchema: { type: "object", properties: {} },
        },
        {
          name: "get_cross_venue_rates",
          description:
            "Compare rates across Mento and Uniswap V3 on Celo. Returns per-pair Mento rate, Uniswap rate, forex rate, and venue spread for cross-DEX arbitrage.",
          inputSchema: { type: "object", properties: {} },
        },
        {
          name: "get_signals",
          description:
            "Get current FX and market trading signals generated by Claude AI analysis.",
          inputSchema: {
            type: "object",
            properties: {
              market: {
                type: "string",
                description:
                  "Filter by market: mento, forex, crypto, commodities",
              },
            },
          },
        },
        {
          name: "get_trades",
          description:
            "Get on-chain Mento swap trades with verifiable Celoscan transaction hashes.",
          inputSchema: { type: "object", properties: {} },
        },
        {
          name: "get_performance",
          description:
            "Get agent verified track record: total volume, P&L, success rate, and on-chain proof.",
          inputSchema: { type: "object", properties: {} },
        },
        {
          name: "get_agent_info",
          description:
            "Get agent identity: ERC-8004 registration, protocols (MCP, A2A, x402), capabilities.",
          inputSchema: { type: "object", properties: {} },
        },
      ],
      prompts: [
        {
          name: "fx_analysis",
          description:
            "Analyze current FX spreads between Mento on-chain rates and real forex rates",
        },
        {
          name: "portfolio_rebalance",
          description:
            "Check portfolio drift and generate rebalance recommendations",
        },
      ],
      resources: [
        {
          uri: "celofx://rates",
          name: "Live FX Rates",
          description: "Real-time Mento vs Forex rate comparison",
        },
        {
          uri: "celofx://trades",
          name: "Trade History",
          description: "On-chain verified swap history",
        },
      ],
      x402: {
        supported: true,
        endpoint: "https://celofx.vercel.app/api/premium-signals",
        price: "$0.01",
        currency: "cUSD",
        chain: "celo",
      },
    },
    {
      headers: {
        "Cache-Control": "public, max-age=0, s-maxage=60",
        "Access-Control-Allow-Origin": "*",
      },
    }
  );
}
