import { NextResponse } from "next/server";
import { getAgentStatus } from "@/lib/agent-policy";
import { getAttestation } from "@/lib/tee";
import { getBaseUrl } from "@/lib/format";

export const dynamic = "force-dynamic";

export async function GET() {
  const agentStatus = getAgentStatus();
  const tee = await getAttestation();
  const base = getBaseUrl();
  const mcpTools = [
    {
      name: "get_mento_rates",
      description: "Get live Mento Broker on-chain stablecoin exchange rates on Celo, compared with real forex rates. Returns spread analysis showing arbitrage opportunities.",
    },
    {
      name: "get_signals",
      description: "Get current FX and market trading signals generated by the CeloFX agent's Claude AI analysis.",
    },
    {
      name: "get_trades",
      description: "Get on-chain Mento swap trades executed by the CeloFX agent. Every trade has a verifiable Celoscan transaction hash.",
    },
    {
      name: "get_performance",
      description: "Get the CeloFX agent's verified track record: total volume, P&L, success rate, and on-chain proof.",
    },
    {
      name: "get_agent_info",
      description: "Get CeloFX agent identity: ERC-8004 registration, on-chain addresses, supported protocols, and capabilities.",
    },
  ];
  const mcpPrompts = [
    { name: "fx_analysis", description: "Analyze current FX spreads between Mento on-chain rates and real forex rates." },
    { name: "portfolio_rebalance", description: "Check portfolio drift and generate rebalance recommendations." },
  ];
  const mcpResources = [
    { uri: "celofx://rates", name: "Live FX Rates" },
    { uri: "celofx://trades", name: "Trade History" },
  ];

  return NextResponse.json(
    {
      type: "https://eips.ethereum.org/EIPS/eip-8004#registration-v1",
      name: "CeloFX",
      description:
        "Autonomous FX arbitrage agent on Celo. Monitors Mento Broker and Uniswap V3 rates versus real forex references, identifies profitable stablecoin spreads, and executes swaps when policy and risk checks pass. Multi-protocol: MCP, A2A, x402, ERC-8004, OASF.",
      image: `${base}/celofx-logo.png`,
      agent_url: base,
      version: "1.1.0",
      documentation: `${base}/developers`,
      openapi: `${base}/api/openapi.json`,
      agent_type: "autonomous_agent",
      owner_wallet: "0x6652AcDc623b7CCd52E115161d84b949bAf3a303",
      mcp_server: `${base}/api/mcp`,
      a2a_endpoint: `${base}/.well-known/agent-card.json`,
      tags: ["fx", "arbitrage", "celo", "stablecoins", "defi"],
      categories: ["finance", "trading", "payments"],
      capabilities: [
        "mcp",
        "a2a",
        "x402",
        "on_chain_execution",
        "policy_checked_trading",
        "cross_venue_rate_comparison",
        "moonpay_fiat_onramp",
        "moonpay_fiat_offramp",
        "moonpay_cross_chain_bridge",
      ],
      moonpay: {
        integration: "MCP client — CeloFX connects to MoonPay CLI MCP server for fiat on/off-ramp, cross-chain bridging, and token swaps",
        mcpConfig: { command: "mp", args: ["mcp"] },
        capabilities: ["fiat_onramp", "fiat_offramp", "token_swap", "token_bridge", "virtual_accounts", "x402_payments"],
      },
      endpoints: {
        web: base,
        mcp: `${base}/api/mcp`,
        a2a: `${base}/.well-known/agent-card.json`,
        mcp_manifest: `${base}/.well-known/mcp.json`,
        agent_discovery: `${base}/.well-known/agent.json`,
        health: `${base}/api/health`,
        openapi: `${base}/api/openapi.json`,
        access_layers: `${base}/api/access-layers`,
      },
      access_layers: [
        {
          id: "eoa_signed",
          auth: "wallet_signature",
          endpoint: `${base}/api/remittance/execute`,
          audience: "wallet_users",
        },
        {
          id: "agent_api",
          auth: "hmac_or_bearer",
          endpoint: `${base}/api/remittance/execute`,
          audience: "agents_apps",
        },
      ],
      services: [
        { type: "web", endpoint: base },
        { type: "discovery", endpoint: `${base}/.well-known/agent.json` },
        {
          type: "mcp",
          endpoint: `${base}/api/mcp`,
          version: "2025-06-18",
          protocolVersion: "2025-06-18",
          serverInfo: { name: "CeloFX MCP Server", version: "1.0.0" },
          tools: mcpTools,
          mcpTools,
          prompts: mcpPrompts,
          resources: mcpResources,
          tools_count: mcpTools.length,
          prompts_count: mcpPrompts.length,
          resources_count: mcpResources.length,
        },
        {
          type: "a2a",
          endpoint:
            `${base}/.well-known/agent-card.json`,
          version: "0.3.0",
          skills: [
            {
              id: "fx_rate_analysis",
              name: "FX Rate Analysis",
              description: "Compares live Mento Broker on-chain stablecoin rates with real forex rates (EUR/USD, USD/BRL) to identify arbitrage spreads.",
            },
            {
              id: "execute_swap",
              name: "Execute Mento Swap",
              description: "Executes a Mento Broker stablecoin swap on Celo mainnet using CIP-64 fee abstraction (gas paid in cUSD).",
            },
            {
              id: "portfolio_status",
              name: "Portfolio Status",
              description: "Returns agent execution wallet balances, recent on-chain trades with Celoscan links, and trade statistics.",
            },
            {
              id: "performance_tracking",
              name: "Performance Tracking",
              description: "Returns the agent's verified track record: total volume, cumulative P&L, success rate, pairs traded.",
            },
          ],
          a2aSkills: [
            {
              id: "fx_rate_analysis",
              name: "FX Rate Analysis",
              description: "Compares live Mento Broker on-chain stablecoin rates with real forex rates (EUR/USD, USD/BRL) to identify arbitrage spreads.",
            },
            {
              id: "execute_swap",
              name: "Execute Mento Swap",
              description: "Executes a Mento Broker stablecoin swap on Celo mainnet using CIP-64 fee abstraction (gas paid in cUSD).",
            },
            {
              id: "portfolio_status",
              name: "Portfolio Status",
              description: "Returns agent execution wallet balances, recent on-chain trades with Celoscan links, and trade statistics.",
            },
            {
              id: "performance_tracking",
              name: "Performance Tracking",
              description: "Returns the agent's verified track record: total volume, cumulative P&L, success rate, pairs traded.",
            },
          ],
        },
        {
          type: "x402",
          endpoint: `${base}/api/premium-signals`,
          version: "1.0.0",
          supported: true,
          x402_supported: true,
          price: "$0.10",
          currency: "cUSD",
          chain: "celo",
          standard: "EIP-712",
        },
        {
          type: "TEE",
          endpoint: `${base}/api/tee/attestation`,
          version: "dstack-dev-0.5.6",
          status: tee.status,
          verified: tee.verified,
          infrastructure: tee.verified ? "Intel TDX (Phala Cloud)" : "CapRover (Hetzner)",
        },
        {
          type: "OASF",
          endpoint: `${base}/.well-known/oasf.json`,
          version: "0.8.0",
          skills: [
            { id: 501, name: "Mathematical Reasoning" },
            { id: 1401, name: "API Schema Understanding" },
            { id: 1402, name: "Workflow Automation" },
            { id: 1501, name: "Strategic Planning" },
            { id: 1504, name: "Hypothesis Generation" },
          ],
          domains: [
            { id: 203, name: "Investment Services" },
            { id: 202, name: "Finance" },
            { id: 109, name: "Blockchain" },
            { id: 10902, name: "Decentralized Finance (DeFi)" },
            { id: 405, name: "Risk Management" },
          ],
          capabilities: [
            "autonomous_execution",
            "on_chain_verification",
            "cross_market_analysis",
            "multi_venue_arbitrage",
            "portfolio_hedging",
            "gas_optimization",
          ],
        },
        {
          type: "agentWallet",
          endpoint: "eip155:42220:0x6652AcDc623b7CCd52E115161d84b949bAf3a303",
        },
      ],
      health: {
        endpoint: `${base}/api/health`,
        interval: 60,
        status: agentStatus.paused ? "paused" : "healthy",
        dailyVolumeUsed: agentStatus.dailyVolume,
        dailyVolumeLimit: agentStatus.dailyLimit,
        decisionsLogged: agentStatus.decisionsLogged,
      },
      x402Support: true,
      x402_supported: true,
      x402: {
        supported: true,
        endpoint: `${base}/api/premium-signals`,
        price: "$0.10",
        currency: "cUSD",
        chain: "celo",
        standard: "EIP-712",
      },
      payment: {
        protocol: "x402",
        supported: true,
        endpoint: `${base}/api/premium-signals`,
        amount: "0.10",
        currency: "cUSD",
      },
      active: !agentStatus.paused,
      updatedAt: new Date().toISOString(),
      registrations: [
        {
          agentId: 10,
          agentRegistry:
            "eip155:42220:0x8004A169FB4a3325136EB29fA0ceB6D2e539a432",
        },
      ],
      registry: {
        chainId: 42220,
        tokenId: "10",
        contract: "0x8004A169FB4a3325136EB29fA0ceB6D2e539a432",
      },
      canonicalIdentity: {
        canonicalAgentId: 10,
        wallet: "0x6652AcDc623b7CCd52E115161d84b949bAf3a303",
        canonicalUrl: "https://www.8004scan.io/agents/celo/10",
        deprecatedAgentIds: [26],
      },
      supportedTrust: ["reputation", "tee-attestation", "crypto-economic"],
      tee: {
        status: tee.status,
        verified: tee.verified,
        infrastructure: tee.verified ? "Intel TDX (Phala Cloud)" : "CapRover (Hetzner)",
        attestationEndpoint: `${base}/api/tee/attestation`,
      },
    },
    {
      headers: {
        "Cache-Control": "public, max-age=0, s-maxage=60",
        "Access-Control-Allow-Origin": "*",
      },
    }
  );
}
