import { NextResponse } from "next/server";
import { getAgentStatus } from "@/lib/agent-policy";
import { getAttestation } from "@/lib/tee";
import { getBaseUrl } from "@/lib/format";

export const dynamic = "force-dynamic";

export async function GET() {
  const agentStatus = getAgentStatus();
  const tee = await getAttestation();
  const base = getBaseUrl();
  const mcpTools = [
    {
      name: "get_mento_rates",
      description: "Get live Mento Broker on-chain stablecoin exchange rates on Celo, compared with real forex rates. Returns spread analysis showing arbitrage opportunities.",
    },
    {
      name: "get_signals",
      description: "Get current FX and market trading signals generated by the CeloFX agent's Claude AI analysis.",
    },
    {
      name: "get_trades",
      description: "Get on-chain Mento swap trades executed by the CeloFX agent. Every trade has a verifiable Celoscan transaction hash.",
    },
    {
      name: "get_performance",
      description: "Get the CeloFX agent's verified track record: total volume, P&L, success rate, and on-chain proof.",
    },
    {
      name: "get_agent_info",
      description: "Get CeloFX agent identity: ERC-8004 registration, on-chain addresses, supported protocols, and capabilities.",
    },
  ];
  const mcpPrompts = [
    { name: "fx_analysis", description: "Analyze current FX spreads between Mento on-chain rates and real forex rates." },
    { name: "portfolio_rebalance", description: "Check portfolio drift and generate rebalance recommendations." },
  ];
  const mcpResources = [
    { uri: "celofx://rates", name: "Live FX Rates" },
    { uri: "celofx://trades", name: "Trade History" },
  ];

  return NextResponse.json(
    {
      type: "https://eips.ethereum.org/EIPS/eip-8004#registration-v1",
      name: "CeloFX",
      description:
        "Autonomous FX arbitrage agent on Celo. Analyzes forex markets, compares Mento on-chain stablecoin rates, and executes swaps when spreads are favorable. Powered by Claude AI.",
      image: `${base}/celofx-logo.png`,
      agent_url: base,
      agent_type: "autonomous_agent",
      owner_wallet: "0x6652AcDc623b7CCd52E115161d84b949bAf3a303",
      mcp_server: `${base}/api/mcp`,
      a2a_endpoint: `${base}/.well-known/agent-card.json`,
      tags: ["fx", "arbitrage", "celo", "stablecoins", "defi"],
      categories: ["finance", "trading", "payments"],
      capabilities: [
        "mcp",
        "a2a",
        "x402",
        "on_chain_execution",
        "policy_checked_trading",
        "cross_venue_rate_comparison",
      ],
      endpoints: {
        web: base,
        mcp: `${base}/api/mcp`,
        a2a: `${base}/.well-known/agent-card.json`,
        mcp_manifest: `${base}/.well-known/mcp.json`,
        agent_discovery: `${base}/.well-known/agent.json`,
        health: `${base}/api/health`,
      },
      services: [
        { name: "web", endpoint: base },
        { name: "discovery", endpoint: `${base}/.well-known/agent.json` },
        {
          name: "mcp",
          endpoint: `${base}/api/mcp`,
          version: "2025-06-18",
          protocolVersion: "2025-06-18",
          serverInfo: { name: "CeloFX MCP Server", version: "1.0.0" },
          tools: mcpTools,
          mcpTools,
          prompts: mcpPrompts,
          resources: mcpResources,
          tools_count: mcpTools.length,
          prompts_count: mcpPrompts.length,
          resources_count: mcpResources.length,
        },
        {
          name: "a2a",
          endpoint:
            `${base}/.well-known/agent-card.json`,
          version: "0.3.0",
          skills: [
            {
              id: "fx_rate_analysis",
              name: "FX Rate Analysis",
              description: "Compares live Mento Broker on-chain stablecoin rates with real forex rates (EUR/USD, USD/BRL) to identify arbitrage spreads.",
            },
            {
              id: "execute_swap",
              name: "Execute Mento Swap",
              description: "Executes a Mento Broker stablecoin swap on Celo mainnet using CIP-64 fee abstraction (gas paid in cUSD).",
            },
            {
              id: "portfolio_status",
              name: "Portfolio Status",
              description: "Returns agent execution wallet balances, recent on-chain trades with Celoscan links, and trade statistics.",
            },
            {
              id: "performance_tracking",
              name: "Performance Tracking",
              description: "Returns the agent's verified track record: total volume, cumulative P&L, success rate, pairs traded.",
            },
          ],
          a2aSkills: [
            {
              id: "fx_rate_analysis",
              name: "FX Rate Analysis",
              description: "Compares live Mento Broker on-chain stablecoin rates with real forex rates (EUR/USD, USD/BRL) to identify arbitrage spreads.",
            },
            {
              id: "execute_swap",
              name: "Execute Mento Swap",
              description: "Executes a Mento Broker stablecoin swap on Celo mainnet using CIP-64 fee abstraction (gas paid in cUSD).",
            },
            {
              id: "portfolio_status",
              name: "Portfolio Status",
              description: "Returns agent execution wallet balances, recent on-chain trades with Celoscan links, and trade statistics.",
            },
            {
              id: "performance_tracking",
              name: "Performance Tracking",
              description: "Returns the agent's verified track record: total volume, cumulative P&L, success rate, pairs traded.",
            },
          ],
        },
        {
          name: "x402",
          endpoint: `${base}/api/premium-signals`,
          version: "1.0.0",
          supported: true,
          x402_supported: true,
          price: "$0.10",
          currency: "cUSD",
          chain: "celo",
          standard: "EIP-712",
        },
        {
          name: "TEE",
          endpoint: `${base}/api/tee/attestation`,
          version: "dstack-dev-0.5.6",
          status: tee.status,
          verified: tee.verified,
          infrastructure: tee.verified ? "Intel TDX (Phala Cloud)" : "Vercel",
        },
        {
          name: "OASF",
          endpoint: `${base}/.well-known/oasf.json`,
          version: "0.8.0",
          skills: [
            { id: 501, name: "Mathematical Reasoning" },
            { id: 1401, name: "API Schema Understanding" },
            { id: 1402, name: "Workflow Automation" },
            { id: 1501, name: "Strategic Planning" },
            { id: 1504, name: "Hypothesis Generation" },
          ],
          domains: [
            { id: 203, name: "Investment Services" },
            { id: 202, name: "Finance" },
            { id: 109, name: "Blockchain" },
            { id: 10902, name: "Decentralized Finance (DeFi)" },
            { id: 405, name: "Risk Management" },
          ],
          capabilities: [
            "autonomous_execution",
            "on_chain_verification",
            "cross_market_analysis",
            "multi_venue_arbitrage",
            "portfolio_hedging",
            "gas_optimization",
          ],
        },
      ],
      health: {
        endpoint: `${base}/api/health`,
        interval: 60,
        status: agentStatus.paused ? "paused" : "healthy",
        dailyVolumeUsed: agentStatus.dailyVolume,
        dailyVolumeLimit: agentStatus.dailyLimit,
        decisionsLogged: agentStatus.decisionsLogged,
      },
      x402Support: true,
      x402_supported: true,
      x402: {
        supported: true,
        endpoint: `${base}/api/premium-signals`,
        price: "$0.10",
        currency: "cUSD",
        chain: "celo",
        standard: "EIP-712",
      },
      payment: {
        protocol: "x402",
        supported: true,
        endpoint: `${base}/api/premium-signals`,
        amount: "0.10",
        currency: "cUSD",
      },
      active: !agentStatus.paused,
      updatedAt: new Date().toISOString(),
      registrations: [
        {
          agentId: 10,
          agentRegistry:
            "eip155:42220:0x8004A169FB4a3325136EB29fA0ceB6D2e539a432",
        },
      ],
      supportedTrust: ["reputation", "tee-attestation", "crypto-economic"],
      tee: {
        status: tee.status,
        verified: tee.verified,
        infrastructure: tee.verified ? "Intel TDX (Phala Cloud)" : "Vercel",
        attestationEndpoint: `${base}/api/tee/attestation`,
      },
    },
    {
      headers: {
        "Cache-Control": "public, max-age=0, s-maxage=60",
        "Access-Control-Allow-Origin": "*",
      },
    }
  );
}
