import { NextResponse } from "next/server";
import { getAgentStatus } from "@/lib/agent-policy";
import { getAttestation } from "@/lib/tee";

export const dynamic = "force-dynamic";

export async function GET() {
  const agentStatus = getAgentStatus();
  const tee = await getAttestation();

  return NextResponse.json(
    {
      type: "https://eips.ethereum.org/EIPS/eip-8004#registration-v1",
      name: "CeloFX",
      description:
        "Autonomous FX arbitrage agent on Celo. Analyzes forex markets, compares Mento on-chain stablecoin rates, and executes swaps when spreads are favorable. Powered by Claude AI.",
      image: "https://celofx.vercel.app/celofx-logo.png",
      services: [
        { name: "web", endpoint: "https://celofx.vercel.app" },
        {
          name: "MCP",
          endpoint: "https://celofx.vercel.app/api/mcp",
          version: "2025-06-18",
          tools: [
            {
              name: "get_mento_rates",
              description: "Get live Mento Broker on-chain stablecoin exchange rates on Celo, compared with real forex rates. Returns spread analysis showing arbitrage opportunities.",
            },
            {
              name: "get_signals",
              description: "Get current FX and market trading signals generated by the CeloFX agent's Claude AI analysis.",
            },
            {
              name: "get_trades",
              description: "Get on-chain Mento swap trades executed by the CeloFX agent. Every trade has a verifiable Celoscan transaction hash.",
            },
            {
              name: "get_performance",
              description: "Get the CeloFX agent's verified track record: total volume, P&L, success rate, and on-chain proof.",
            },
            {
              name: "get_agent_info",
              description: "Get CeloFX agent identity: ERC-8004 registration, on-chain addresses, supported protocols, and capabilities.",
            },
          ],
        },
        {
          name: "A2A",
          endpoint:
            "https://celofx.vercel.app/.well-known/agent-card.json",
          version: "0.3.0",
          skills: [
            {
              id: "fx_rate_analysis",
              name: "FX Rate Analysis",
              description: "Compares live Mento Broker on-chain stablecoin rates with real forex rates (EUR/USD, USD/BRL) to identify arbitrage spreads.",
            },
            {
              id: "execute_swap",
              name: "Execute Mento Swap",
              description: "Executes a Mento Broker stablecoin swap on Celo mainnet using CIP-64 fee abstraction (gas paid in cUSD).",
            },
            {
              id: "portfolio_status",
              name: "Portfolio Status",
              description: "Returns agent execution wallet balances, recent on-chain trades with Celoscan links, and trade statistics.",
            },
            {
              id: "performance_tracking",
              name: "Performance Tracking",
              description: "Returns the agent's verified track record: total volume, cumulative P&L, success rate, pairs traded.",
            },
          ],
        },
        {
          name: "X402",
          endpoint: "https://celofx.vercel.app/api/premium-signals",
          version: "1.0.0",
          price: "$0.01",
          currency: "cUSD",
          chain: "celo",
          standard: "EIP-712",
        },
        {
          name: "TEE",
          endpoint: "https://celofx.vercel.app/api/tee/attestation",
          version: "dstack-dev-0.5.6",
          status: tee.status,
          verified: tee.verified,
          infrastructure: tee.verified ? "Intel TDX (Phala Cloud)" : "Vercel",
        },
        {
          name: "OASF",
          endpoint: "https://github.com/agntcy/oasf/",
          version: "0.8.0",
          skills: [
            "analytical_skills/mathematical_reasoning",
            "analytical_skills/data_analysis",
            "tool_interaction/api_integration",
            "tool_interaction/blockchain_interaction",
            "advanced_reasoning_planning/strategic_planning",
            "advanced_reasoning_planning/risk_assessment",
          ],
          domains: [
            "finance_and_business/investment_services",
            "finance_and_business/foreign_exchange",
            "finance_and_business/risk_management",
            "technology/blockchain",
            "technology/defi",
          ],
          capabilities: [
            "autonomous_execution",
            "on_chain_verification",
            "cross_market_analysis",
            "multi_venue_arbitrage",
            "portfolio_hedging",
            "gas_optimization",
          ],
        },
      ],
      health: {
        endpoint: "https://celofx.vercel.app/api/health",
        interval: 60,
        status: agentStatus.paused ? "paused" : "healthy",
        dailyVolumeUsed: agentStatus.dailyVolume,
        dailyVolumeLimit: agentStatus.dailyLimit,
        decisionsLogged: agentStatus.decisionsLogged,
      },
      x402Support: true,
      active: !agentStatus.paused,
      updatedAt: new Date().toISOString(),
      registrations: [
        {
          agentId: 10,
          agentRegistry:
            "eip155:42220:0x8004A169FB4a3325136EB29fA0ceB6D2e539a432",
        },
      ],
      supportedTrust: ["reputation", "tee-attestation", "crypto-economic"],
      tee: {
        status: tee.status,
        verified: tee.verified,
        infrastructure: tee.verified ? "Intel TDX (Phala Cloud)" : "Vercel",
        attestationEndpoint: "https://celofx.vercel.app/api/tee/attestation",
      },
    },
    {
      headers: {
        "Cache-Control": "public, max-age=0, s-maxage=60",
        "Access-Control-Allow-Origin": "*",
      },
    }
  );
}
