import { createMcpHandler } from "mcp-handler";
import { z } from "zod";
import { getMentoOnChainRates } from "@/lib/mento-sdk";
import { getSignals } from "@/lib/signal-store";
import { getTrades } from "@/lib/trade-store";

const handler = createMcpHandler(
  (server) => {
    server.registerTool(
      "get_mento_rates",
      {
        title: "Get Mento Rates",
        description:
          "Get live Mento Broker on-chain stablecoin exchange rates on Celo, compared with real forex rates",
        inputSchema: {},
      },
      async () => {
        try {
          const rates = await getMentoOnChainRates();
          return {
            content: [{ type: "text" as const, text: JSON.stringify(rates) }],
          };
        } catch {
          return {
            content: [
              {
                type: "text" as const,
                text: JSON.stringify({ error: "Failed to fetch Mento rates" }),
              },
            ],
          };
        }
      }
    );

    server.registerTool(
      "get_signals",
      {
        title: "Get Trading Signals",
        description:
          "Get current FX and market trading signals generated by the CeloFX agent",
        inputSchema: {
          market: z
            .string()
            .optional()
            .describe("Filter by market: mento, forex, crypto, commodities"),
        },
      },
      async ({ market }) => {
        const signals = getSignals();
        const filtered = market
          ? signals.filter((s) => s.market === market)
          : signals;
        return {
          content: [
            {
              type: "text" as const,
              text: JSON.stringify({
                count: filtered.length,
                signals: filtered.slice(0, 10),
              }),
            },
          ],
        };
      }
    );

    server.registerTool(
      "get_trades",
      {
        title: "Get Executed Trades",
        description:
          "Get on-chain Mento swap trades executed by the CeloFX agent, with Celoscan tx hashes",
        inputSchema: {},
      },
      async () => {
        const trades = getTrades();
        return {
          content: [
            {
              type: "text" as const,
              text: JSON.stringify({
                count: trades.length,
                trades: trades.map((t) => ({
                  pair: t.pair,
                  amountIn: t.amountIn,
                  amountOut: t.amountOut,
                  rate: t.rate,
                  status: t.status,
                  swapTxHash: t.swapTxHash,
                })),
              }),
            },
          ],
        };
      }
    );

    server.registerTool(
      "get_agent_info",
      {
        title: "Get Agent Info",
        description:
          "Get CeloFX agent metadata: ERC-8004 identity, capabilities, and on-chain addresses",
        inputSchema: {},
      },
      async () => {
        return {
          content: [
            {
              type: "text" as const,
              text: JSON.stringify({
                name: "CeloFX",
                agentId: 4,
                chain: "Celo",
                chainId: 42220,
                registry: "0x8004A169FB4a3325136EB29fA0ceB6D2e539a432",
                reputationRegistry:
                  "0x8004BAa17C55a88189AE136b182e5fdA19dE9b63",
                broker: "0x777A8255cA72412f0d706dc03C9D1987306B4CaD",
                capabilities: [
                  "mento_rates",
                  "forex_analysis",
                  "signal_generation",
                  "swap_execution",
                  "x402_micropayments",
                  "fee_abstraction",
                ],
                website: "https://celofx.vercel.app",
              }),
            },
          ],
        };
      }
    );
  },
  {},
  { basePath: "/api", maxDuration: 60 }
);

export { handler as GET, handler as POST };
