import type { Trade } from "./types";

const now = Date.now();
const h = (hours: number) => now - hours * 60 * 60 * 1000;

export const seedTrades: Trade[] = [
  {
    id: "trade-seed-1",
    pair: "cUSD/cEUR",
    fromToken: "cUSD",
    toToken: "cEUR",
    amountIn: "500",
    amountOut: "418.92",
    rate: 0.8378,
    spreadPct: 0.42,
    status: "confirmed",
    approvalTxHash: "0x8a3f...7e2b",
    swapTxHash: "0x1d4c...9f3a",
    pnl: 2.1,
    timestamp: h(3),
  },
  {
    id: "trade-seed-2",
    pair: "cUSD/cREAL",
    fromToken: "cUSD",
    toToken: "cREAL",
    amountIn: "200",
    amountOut: "1039.40",
    rate: 5.197,
    spreadPct: 0.15,
    status: "confirmed",
    approvalTxHash: "0xb7e2...4a1c",
    swapTxHash: "0x3f8d...c5e7",
    pnl: 0.3,
    timestamp: h(8),
  },
  {
    id: "trade-seed-3",
    pair: "cUSD/cEUR",
    fromToken: "cUSD",
    toToken: "cEUR",
    amountIn: "1000",
    amountOut: "0",
    rate: 0.8355,
    spreadPct: -0.69,
    status: "failed",
    approvalTxHash: "0xc4a9...8d2f",
    error: "Swap reverted: amountOut below minimum",
    timestamp: h(12),
  },
  {
    id: "trade-seed-4",
    pair: "cEUR/cUSD",
    fromToken: "cEUR",
    toToken: "cUSD",
    amountIn: "300",
    amountOut: "355.20",
    rate: 1.184,
    spreadPct: 0.31,
    status: "confirmed",
    approvalTxHash: "0xd5f1...6b3e",
    swapTxHash: "0x7e2a...1d4c",
    pnl: 0.93,
    timestamp: h(18),
  },
];
